<?php $enabled = $block->getPackingsSetting(); ?>
<?php if($enabled): ?>
<form>
     <div class="form">
        <div class="form-group">
        <div class="label">
        <label for="units"><span>Enter Box dimensions (Current store units set to <?php echo $block->getUnits(); ?>)</span></label><br><br>
        </div>
        <div style="margin-left:5%">
            <table>
                <tr>
                    <td>
                        <label for="box model" class="form-label"> Box Model </label>
                    </td>
                    <td>
                        <input type="text" class="form-element input-text admin__control-text" name="model" placeholder="Box Model" required /><br />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="length" class="form-label"> Length </label>
                    </td>
                    <td>
                        <input type="text" class="form-element input-text admin__control-text" name="length" placeholder="Length" required /><br />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="width" class="form-label"> Width </label>
                    </td>
                    <td>
                        <input type="text" class="form-element input-text admin__control-text" name="width" placeholder="Width" required /><br />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="height" class="form-label"> Height </label>
                    </td>
                    <td>
                        <input type="text" class="form-element input-text admin__control-text" name="height" placeholder="Height" required />
                </tr>
                <tr>
                    <td>
                        <label for="weight" class="form-label"> Weight </label>
                    </td>
                    <td>
                        <input type="text" class="form-element input-text admin__control-text" name="weight" placeholder="Weight of empty box" required /><br />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="max weight" class="form-label"> Max Weight </label>
                    </td>
                    <td>
                        <input type="text" class="form-element input-text admin__control-text" name="maxWeight" placeholder="Maximum Weight this box can carry" required /><br />
                    </td>
                </tr>
                <?php if($block->showBoxPrice()): ?>
                <tr>
                    <td>
                        <label for="price" class="form-label"> Price </label>
                    </td>
                    <td>
                        <input type="text" class="form-element input-text admin__control-text" name="price" placeholder="Box Price" required /><br />
                    </td>
                </tr>
                <?php endif; ?>
                <tr>
                    <td>
                        <button type="submit" class="form-element action-primary scalable save" style="margin-left:50%;">Save</button>
                </tr>
            </table>
            
        </div>
  </div> 
</form>
<?php else: ?>
    <p>You need to Enable Packings under Configuration to set boxes</p>
<?php endif; ?>
<style>
    .form-label{
        font-weight: bold;
    }
    .form-element{
        margin:15px;
        width:80%;
    }
</style>
