<form>
    <?php
        echo "<b>".$block->getTitle()."</b><br><br>";
    ?>
    <p>Any shipments made in the test environment will only be for testing. These cannot be shipped.</p>
    <br>
  <div class="form-group">

    <div class="label">
    <label for="token"><span>Enter API Token</span></label>
    <?php if($block->isTokenSet()) : ?>
      <input type="text" class="input-text admin__control-text" name="api_token"/>
    <?php else : ?>
      <input type="text" class="input-text admin__control-text" name="api_token" required/>
    <?php endif; ?>
    </div>
    <br>

    <div class="label">
    <label for="env"><span>Enable Test Environment</span></label>
      <select class="select admin__control-select" name="test_env">
          <?php $text = $block->getSettings()['test_env'] ? 'Yes' : 'No'; ?>
          <option value="<?= $block->getSettings()['test_env']; ?>" selected="selected"><?= $text ?></option>
          <?php $text = !$block->getSettings()['test_env'] ? 'Yes' : 'No'; ?>
          <option value="<?= !$block->getSettings()['test_env']; ?>" ><?= $text ?></option>
      </select>
      </div>
      <br>

    <div class="label">
    <label for="packing"><span>Enable Packings</span></label>
      <select class="select admin__control-select" name="packings">

          <?php $text = $block->getSettings()['packings'] ? 'Yes' : 'No'; ?>
          <option value="<?= $block->getSettings()['packings']; ?>" selected="selected"><?= $text ?></option>
          <?php $text = !$block->getSettings()['packings'] ? 'Yes' : 'No'; ?>
          <option value="<?= !$block->getSettings()['packings']; ?>" ><?= $text ?></option>
      </select>
      </div>
      <br>

    <div class="label">
    <label for="logging"><span>Enable Logging</span></label>
      <select class="select admin__control-select" name="logging">

          <?php $text = $block->getSettings()['log'] ? 'Yes' : 'No'; ?>
          <option value="<?= $block->getSettings()['log']; ?>" selected="selected"><?= $text ?></option>
          <?php $text = !$block->getSettings()['log'] ? 'Yes' : 'No'; ?>
          <option value="<?= !$block->getSettings()['log']; ?>" ><?= $text ?></option>
      </select>
      </div>
      <br>
    <button type="submit" class="action-primary scalable save">Save</button>

</div>

</form>
</body>
