<section class="admin__page-section order-view-packing">
    <div class="admin__page-section-title">
        <span class="title">FlagShip Packing Details</span>
    </div>
    <div class="admin__page-section-content">
        <?php

            if(is_null($block->getBoxes())){
                $packingDetails = 'Please set at least one box';
                echo $packingDetails;
                return;
            }

            if(!$block->isPackingEnabled()){
                $packingDetails = 'Packing suggestions are disabled. Please enable it under FlagShip Configuration.';
                echo $packingDetails;
                return;
            }

            $packings = $block->getPacking()['packingDetails'];
            if(!is_null($packings)){
                $packingDetails = $block->getPackingDetails();
            }

            $packing = '';
            foreach ($packingDetails as $packingDetail) {
                $packing .= normalizePackingDetail($packingDetail['detail']);
            }

            $shipAsIs = $block->getPacking()['shipAsIs'];
            $detail = '';
            if(count($shipAsIs) != 0){
                $packing .= '<br>Ship following products <b>in product packaging </b>';
                foreach ($shipAsIs as $value) {
                    $packing .= normalizeShipAsIs($value,$detail);
                }
            }
            echo $packing;

            function normalizePackingDetail($packingDetail){
                $packingSuggestions = '';
                foreach ($packingDetail as $key => $value) {
                    $packingSuggestions .= 'Use box <b>'.$key.'</b> to pack <br>'.getItems($value);
                }
                return $packingSuggestions;
            }

            function getItems($itemCount)
            {
                $detail = '';
                foreach ($itemCount as $key => $value) {
                    $detail .= '<span style="margin-left:5%;"><b>'.$value.'</b> x <b>'.$key.'</b><br>';
                }
                return $detail;
            }

            function normalizeShipAsIs($shipDetail,$detail){
                $detail .= "<br>".$shipDetail."<br>";
                return $detail;
            }
        ?>
    </div>
</section>
